"""unofficial puzzle columns

Revision ID: 3ec0b8925237
Revises: 60613e3fc471
Create Date: 2025-07-10 16:51:56.742707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ec0b8925237'
down_revision: Union[str, None] = '60613e3fc471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sqlmodel.AutoString(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column('author', sqlmodel.AutoString(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column('is_official', sa.Boolean(), nullable=False, server_default='1')
        )

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column(
            'is_official',
            server_default=None,
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_column('is_official')
        batch_op.drop_column('author')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
